### ISSUE TITLE
Uncaught exception

### ISSUE THREAD

**Issue by Cronuh** [DStatIO/StatusSocket#11]
Hey, after enabling the plugin I can't get any data from it. In the RL logs I can see following:

`2023-07-27 16:04:07 CEST [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at com.statussocket.data.player.PlayerDataBuilder.loadSkills(PlayerDataBuilder.java:176)
	at com.statussocket.data.player.PlayerDataBuilder.build(PlayerDataBuilder.java:275)
	at com.statussocket.StatusSocketClient.sendInventoryChangeLog(StatusSocketClient.java:38)
	at com.statussocket.StatusSocketPlugin.onGameTick(StatusSocketPlugin.java:174)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.tick(Hooks.java:211)
	at client.uj(client.java:48124)
	at client.bw(client.java)
	at bq.bd(bq.java:363)
	at bq.run(bq.java:342)
	at java.base/java.lang.Thread.run(Unknown Source)`

**Comment by namcsmd** [comment]
Looks like this NPE was fixed in https://github.com/DStatIO/StatusSocket/pull/8.

However it's still happening today (client version 1.10.14.4) since the plugin hub hasn't been updated yet https://github.com/runelite/plugin-hub/pulls?q=is%3Apr+status+socket

@The-Jani and @DStatIO - can anyone submit a PR to update the plugin hub? I can do so if appropriate - I'd like to see this plugin be functional again.  

```
WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at com.statussocket.data.player.PlayerDataBuilder.loadSkills(PlayerDataBuilder.java:176)
	at com.statussocket.data.player.PlayerDataBuilder.build(PlayerDataBuilder.java:275)
	at com.statussocket.StatusSocketClient.sendInventoryChangeLog(StatusSocketClient.java:38)
	at com.statussocket.StatusSocketPlugin.onGameTick(StatusSocketPlugin.java:174)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.tick(Hooks.java:212)
	at client.bi(client.java:35765)
	at client.ai(client.java)
	at bb.ad(bb.java:358)
	at bb.run(bb.java:335)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by DStatIO** [comment]
I’ll make sure it gets done. To clarify since I haven’t used the plugin since our initial use. The plugin hub hasn’t been updated to the correct version?

**Comment by The-Jani** [comment]
The codebase has indeed been updated to the latest version since the closure of issue #8  .

However, the plugin-hub maintainers have requested the removal of `enabledByDefault = false`, as noted in pull request #10 . Since these changes were not implemented and the commit was not resubmitted, the pull request has been closed.

You can either remove it manually or accept the PR, then commit the new link on the plugin-hub.

For further details, you can refer to the issue comment [here](https://github.com/runelite/plugin-hub/pull/4604#issuecomment-1761529252).


Thanks for your continuous support regarding this plugin. :)

**Comment by DStatIO** [comment]
Made a pull request to push all updates.
